# Generated by Django 5.2.15 on 2026-06-29 04:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blocked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_by', to=settings.AUTH_USER_MODEL)),
                ('blocker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocking', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'social_block',
                'indexes': [models.Index(fields=['blocker'], name='social_bloc_blocker_846063_idx'), models.Index(fields=['blocked'], name='social_bloc_blocked_67400d_idx')],
                'constraints': [models.UniqueConstraint(fields=('blocker', 'blocked'), name='uniq_block_pair'), models.CheckConstraint(condition=models.Q(('blocker', models.F('blocked')), _negated=True), name='block_not_self')],
            },
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following_set', to=settings.AUTH_USER_MODEL)),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'social_follow',
                'indexes': [models.Index(fields=['follower'], name='social_foll_followe_9bcca8_idx'), models.Index(fields=['following'], name='social_foll_followi_3e6f69_idx')],
                'constraints': [models.UniqueConstraint(fields=('follower', 'following'), name='uniq_follow_pair'), models.CheckConstraint(condition=models.Q(('follower', models.F('following')), _negated=True), name='follow_not_self')],
            },
        ),
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=10)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_friend_requests', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_friend_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'social_friend_request',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['to_user', 'status'], name='social_frie_to_user_8f98f6_idx'), models.Index(fields=['from_user', 'status'], name='social_frie_from_us_1205f4_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('from_user', 'to_user'), name='uniq_pending_friend_request'), models.CheckConstraint(condition=models.Q(('from_user', models.F('to_user')), _negated=True), name='friend_request_not_self')],
            },
        ),
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_high', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendships_high', to=settings.AUTH_USER_MODEL)),
                ('user_low', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendships_low', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'social_friendship',
                'indexes': [models.Index(fields=['user_low'], name='social_frie_user_lo_9dda69_idx'), models.Index(fields=['user_high'], name='social_frie_user_hi_2fdef1_idx')],
                'constraints': [models.UniqueConstraint(fields=('user_low', 'user_high'), name='uniq_friendship_pair'), models.CheckConstraint(condition=models.Q(('user_low', models.F('user_high')), _negated=True), name='friendship_not_self')],
            },
        ),
        migrations.CreateModel(
            name='Mute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('until', models.DateTimeField(blank=True, help_text='Null = indefinite', null=True)),
                ('muted', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='muted_by', to=settings.AUTH_USER_MODEL)),
                ('muter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='muting', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'social_mute',
                'constraints': [models.UniqueConstraint(fields=('muter', 'muted'), name='uniq_mute_pair'), models.CheckConstraint(condition=models.Q(('muter', models.F('muted')), _negated=True), name='mute_not_self')],
            },
        ),
    ]
