# Generated by Django 5.2.15 on 2026-06-29 04:23

import apps.profiles.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email_messages', models.BooleanField(default=True)),
                ('email_friend_requests', models.BooleanField(default=True)),
                ('email_mentions', models.BooleanField(default=True)),
                ('push_messages', models.BooleanField(default=True)),
                ('push_friend_requests', models.BooleanField(default=True)),
                ('push_mentions', models.BooleanField(default=True)),
                ('push_calls', models.BooleanField(default=True)),
                ('sound_enabled', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'notification settings',
                'db_table': 'profiles_notification_settings',
            },
        ),
        migrations.CreateModel(
            name='PrivacySettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile_visibility', models.CharField(choices=[('everyone', 'Everyone'), ('friends', 'Friends only'), ('nobody', 'Nobody')], default='everyone', max_length=10)),
                ('last_seen_visibility', models.CharField(choices=[('everyone', 'Everyone'), ('friends', 'Friends only'), ('nobody', 'Nobody')], default='everyone', max_length=10)),
                ('online_status_visibility', models.CharField(choices=[('everyone', 'Everyone'), ('friends', 'Friends only'), ('nobody', 'Nobody')], default='everyone', max_length=10)),
                ('who_can_follow', models.CharField(choices=[('everyone', 'Everyone'), ('friends', 'Friends only'), ('nobody', 'Nobody')], default='everyone', max_length=10)),
                ('who_can_friend_request', models.CharField(choices=[('everyone', 'Everyone'), ('friends', 'Friends only'), ('nobody', 'Nobody')], default='everyone', max_length=10)),
                ('who_can_message', models.CharField(choices=[('everyone', 'Everyone'), ('friends', 'Friends only'), ('nobody', 'Nobody')], default='everyone', max_length=10)),
                ('searchable', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='privacy', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'privacy settings',
                'db_table': 'profiles_privacy_settings',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=apps.profiles.models.avatar_upload_to)),
                ('cover', models.ImageField(blank=True, null=True, upload_to=apps.profiles.models.cover_upload_to)),
                ('bio', models.CharField(blank=True, max_length=500)),
                ('country', models.CharField(blank=True, help_text='ISO 3166-1 alpha-2', max_length=2)),
                ('language', models.CharField(default='en', max_length=10)),
                ('website', models.URLField(blank=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('social_links', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('online', 'Online'), ('away', 'Away'), ('busy', 'Busy'), ('invisible', 'Invisible'), ('offline', 'Offline')], default='online', max_length=12)),
                ('custom_status_text', models.CharField(blank=True, max_length=128)),
                ('custom_status_emoji', models.CharField(blank=True, max_length=32)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'profiles_profile',
            },
        ),
    ]
