# Generated by Django 5.2.15 on 2026-06-29 03:33

import apps.accounts.managers
import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(db_index=True, error_messages={'unique': 'An account with this email already exists.'}, max_length=254, unique=True, verbose_name='email address')),
                ('username', models.CharField(error_messages={'unique': 'This username is already taken.'}, max_length=32, unique=True, validators=[django.core.validators.RegexValidator(message='Username must be 3–32 characters and contain only letters, numbers, and underscores.', regex='^[a-zA-Z0-9_]{3,32}$')], verbose_name='username')),
                ('display_name', models.CharField(blank=True, max_length=80, verbose_name='display name')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive accounts cannot authenticate.', verbose_name='active')),
                ('is_staff', models.BooleanField(default=False, verbose_name='staff status')),
                ('is_email_verified', models.BooleanField(default=False, verbose_name='email verified')),
                ('is_verified', models.BooleanField(default=False, help_text='Official verified account (blue check).', verbose_name='verified badge')),
                ('last_seen_at', models.DateTimeField(blank=True, null=True, verbose_name='last seen')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'db_table': 'accounts_user',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['username'], name='accounts_us_usernam_c0ea66_idx'), models.Index(fields=['is_active', 'is_email_verified'], name='accounts_us_is_acti_cfc41a_idx')],
            },
            managers=[
                ('objects', apps.accounts.managers.UserManager()),
            ],
        ),
    ]
